### PR TITLE
`nanover-ase-omm` and `nanover-omm-server` via OmniRunner instead of older runners

### PR DESCRIPTION
**Pull request by Ragzouken**
Removes trajectory logging and the ability to disable discovery

### CODE REVIEW

**Review by rhoslynroebuck — COMMENTED** [review]
One issue I'm having with every notebook is the below warning the first time I run any nanover import. When I re-run the cell, the warning disappears. Is this something you were having as well @Ragzouken ? Maybe it's an issue specific to my environment or setup?

`nanover-protocol\python-libraries\nanover-core\src\nanover\protocol\command\command_service_pb2_grpc.py:21: RuntimeWarning: The grpc package installed is at version 1.64.0, but the generated code in nanover/protocol/command/command_service_pb2_grpc.py depends on grpcio>=1.64.1. Please upgrade your grpc module to grpcio>=1.64.1 or downgrade your generated code using grpcio-tools<=1.64.0. This warning will become an error in 1.65.0, scheduled for release on June 25, 2024.`

Even with this warning, the tutorials all work as expected for me.

**Comment by Ragzouken** [comment]
> One issue I'm having with every notebook is the below warning the first time I run any nanover import. When I re-run the cell, the warning disappears. Is this something you were having as well @Ragzouken ? Maybe it's an issue specific to my environment or setup?
> 
> `nanover-protocol\python-libraries\nanover-core\src\nanover\protocol\command\command_service_pb2_grpc.py:21: RuntimeWarning: The grpc package installed is at version 1.64.0, but the generated code in nanover/protocol/command/command_service_pb2_grpc.py depends on grpcio>=1.64.1. Please upgrade your grpc module to grpcio>=1.64.1 or downgrade your generated code using grpcio-tools<=1.64.0. This warning will become an error in 1.65.0, scheduled for release on June 25, 2024.`
> 
> Even with this warning, the tutorials all work as expected for me.

Could you rerun the compile script (win_compile or compile) and see if you still get the error? I think it's just complaining that you generated it with a different version (though I'm not sure how that would have happened, so maybe not).

**Comment by rhoslynroebuck** [comment]
> > One issue I'm having with every notebook is the below warning the first time I run any nanover import. When I re-run the cell, the warning disappears. Is this something you were having as well @Ragzouken ? Maybe it's an issue specific to my environment or setup?
> > `nanover-protocol\python-libraries\nanover-core\src\nanover\protocol\command\command_service_pb2_grpc.py:21: RuntimeWarning: The grpc package installed is at version 1.64.0, but the generated code in nanover/protocol/command/command_service_pb2_grpc.py depends on grpcio>=1.64.1. Please upgrade your grpc module to grpcio>=1.64.1 or downgrade your generated code using grpcio-tools<=1.64.0. This warning will become an error in 1.65.0, scheduled for release on June 25, 2024.`
> > Even with this warning, the tutorials all work as expected for me.
> 
> Could you rerun the compile script (win_compile or compile) and see if you still get the error? I think it's just complaining that you generated it with a different version (though I'm not sure how that would have happened, so maybe not).

OK, just did that and I'm not getting the warning anymore. But I guess this could be because I've already run the notebooks? Maybe @Mohamed-Dhouioui or @hjstroud could check on their machines to make sure. We have a meeting tomorrow to check these notebooks together so we can check then.

**Comment by Ragzouken** [comment]
Nanotube loads with weird topology

**Pull request closed without merging**
